FROM node:20-bookworm-slim AS build
ARG APP_DIR
WORKDIR /app
COPY ${APP_DIR}/package*.json ./
RUN npm install
COPY ${APP_DIR}/ ./
RUN npm run build

FROM nginx:1.27-alpine
ARG NGINX_CONF
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
